"""DO NOT EDIT THIS FILE!

This file is auto generated by feishu rest api description.
"""

from typing import TYPE_CHECKING
from functools import cached_property

from .models import *
from .ai import AiClient
from .im import ImClient
from .vc import VcClient
from .acs import AcsClient
from .ccm import CcmClient
from .ehr import EhrClient
from .okr import OkrClient
from .hire import HireClient
from .mail import MailClient
from .task import TaskClient
from .admin import AdminClient
from .baike import BaikeClient
from .event import EventClient
from .authen import AuthenClient
from .search import SearchClient
from .tenant import TenantClient
from .contact import ContactClient
from .approval import ApprovalClient
from .calendar import CalendarClient
from .helpdesk import HelpdeskClient
from .passport import PassportClient
from .attendance import AttendanceClient
from .credential import CredentialClient
from .application import ApplicationClient
from .feishu_people import FeishuPeopleClient
from .human_authentication import HumanAuthenticationClient
from .verification_information import VerificationInformationClient

if TYPE_CHECKING:
    from feishukit import FeishuCore


class RestNamespace:
    def __init__(self, feishu: "FeishuCore"):
        self._feishu = feishu

    @cached_property
    def credential(self) -> CredentialClient:
        return CredentialClient(self._feishu)

    @cached_property
    def authen(self) -> AuthenClient:
        return AuthenClient(self._feishu)

    @cached_property
    def event(self) -> EventClient:
        return EventClient(self._feishu)

    @cached_property
    def contact(self) -> ContactClient:
        return ContactClient(self._feishu)

    @cached_property
    def im(self) -> ImClient:
        return ImClient(self._feishu)

    @cached_property
    def ccm(self) -> CcmClient:
        return CcmClient(self._feishu)

    @cached_property
    def calendar(self) -> CalendarClient:
        return CalendarClient(self._feishu)

    @cached_property
    def vc(self) -> VcClient:
        return VcClient(self._feishu)

    @cached_property
    def attendance(self) -> AttendanceClient:
        return AttendanceClient(self._feishu)

    @cached_property
    def approval(self) -> ApprovalClient:
        return ApprovalClient(self._feishu)

    @cached_property
    def helpdesk(self) -> HelpdeskClient:
        return HelpdeskClient(self._feishu)

    @cached_property
    def task(self) -> TaskClient:
        return TaskClient(self._feishu)

    @cached_property
    def mail(self) -> MailClient:
        return MailClient(self._feishu)

    @cached_property
    def application(self) -> ApplicationClient:
        return ApplicationClient(self._feishu)

    @cached_property
    def tenant(self) -> TenantClient:
        return TenantClient(self._feishu)

    @cached_property
    def search(self) -> SearchClient:
        return SearchClient(self._feishu)

    @cached_property
    def ai(self) -> AiClient:
        return AiClient(self._feishu)

    @cached_property
    def admin(self) -> AdminClient:
        return AdminClient(self._feishu)

    @cached_property
    def ehr(self) -> EhrClient:
        return EhrClient(self._feishu)

    @cached_property
    def hire(self) -> HireClient:
        return HireClient(self._feishu)

    @cached_property
    def okr(self) -> OkrClient:
        return OkrClient(self._feishu)

    @cached_property
    def human_authentication(self) -> HumanAuthenticationClient:
        return HumanAuthenticationClient(self._feishu)

    @cached_property
    def acs(self) -> AcsClient:
        return AcsClient(self._feishu)

    @cached_property
    def baike(self) -> BaikeClient:
        return BaikeClient(self._feishu)

    @cached_property
    def feishu_people(self) -> FeishuPeopleClient:
        return FeishuPeopleClient(self._feishu)

    @cached_property
    def passport(self) -> PassportClient:
        return PassportClient(self._feishu)

    @cached_property
    def verification_information(self) -> VerificationInformationClient:
        return VerificationInformationClient(self._feishu)
