"""DO NOT EDIT THIS FILE!

This file is auto generated by feishu rest api description.
"""


from typing import TYPE_CHECKING, overload

from pydantic import BaseModel, parse_obj_as

if TYPE_CHECKING:
    from feishukit.response import Response


class AcsClient:
    def __init__(self, feishu):
        self._feishu = feishu

    def get_user(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/acs-v1/user/get

        该接口用于获取智能门禁中单个用户的信息。
        """
        ...

    def list_user(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/acs-v1/user/list

        使用该接口获取智能门禁中所有用户信息
        """
        ...

    def patch_user(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/acs-v1/user/patch

        飞书智能门禁在人脸识别成功后会有韦根信号输出，输出用户的卡号。
        对于使用韦根协议的门禁系统，企业可使用该接口录入用户卡号。
        """
        ...

    def update_user_face(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/acs-v1/user-face/update

        用户需要录入人脸图片才可以使用门禁考勤机。使用该 API 上传门禁用户的人脸图片。
        """
        ...

    def get_user_face(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/acs-v1/user-face/get

        对于已经录入人脸图片的用户，可以使用该接口下载用户人脸图片
        """
        ...

    def list_access_record(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/acs-v1/access_record/list

        用户在门禁考勤机上成功开门或打卡后，智能门禁应用都会生成一条门禁记录。

        该接口返回满足查询参数的识别记录
        """
        ...

    def get_access_record_access_photo(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/acs-v1/access_record-access_photo/get

        用户在门禁考勤机上成功开门或打卡后，智能门禁应用都会生成一条门禁记录，对于使用人脸识别方式进行开门的识别记录，还会有抓拍图。

        可以用该接口下载开门时的人脸识别照片
        """
        ...

    def list_device(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/acs-v1/device/list

        使用该接口获取租户内所有设备
        """
        ...
