"""DO NOT EDIT THIS FILE!

This file is auto generated by feishu rest api description.
"""


from typing import TYPE_CHECKING, overload

from pydantic import BaseModel, parse_obj_as

if TYPE_CHECKING:
    from feishukit.response import Response


class AiClient:
    def __init__(self, feishu):
        self._feishu = feishu

    def basic_recognize_image(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/ai/optical_char_recognition-v1/image/basic_recognize

        可识别图片中的文字，按图片中的区域划分，分段返回文本列表
        """
        ...

    def stream_recognize_speech(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/ai/speech_to_text-v1/speech/stream_recognize

        语音流式接口，将整个音频文件分片进行传入模型。能够实时返回数据。建议每个音频分片的大小为 100-200ms
        """
        ...

    def file_recognize_speech(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/ai/speech_to_text-v1/speech/file_recognize

        语音文件识别接口，上传整段语音文件进行一次性识别。接口适合 60 秒以内音频识别
        """
        ...

    def translate_text(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/ai/translation-v1/text/translate

        机器翻译 (MT)，支持以下语种互译：
        "zh": 汉语；
        "zh-Hant": 繁体汉语；
        "en": 英语；
        "ja": 日语；
        "ru": 俄语；
        "de": 德语；
        "fr": 法语；
        "it": 意大利语；
        "pl": 波兰语；
        "th": 泰语；
        "hi": 印地语；
        "id": 印尼语；
        "es": 西班牙语；
        "pt": 葡萄牙语；
        "ko": 朝鲜语；
        "vi": 越南语；
        """
        ...

    def detect_text(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/ai/translation-v1/text/detect

        机器翻译 (MT)，支持 100 多种语言识别，返回符合 ISO 639-1 标准
        """
        ...

    def detect_face_attributes_image(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/ai/face_detection-v1/image/detect_face_attributes

        检测图片中的人脸属性和质量等信息
        """
        ...
