"""DO NOT EDIT THIS FILE!

This file is auto generated by feishu rest api description.
"""


from typing import TYPE_CHECKING, overload

from pydantic import BaseModel, parse_obj_as

if TYPE_CHECKING:
    from feishukit.response import Response


class ApplicationClient:
    def __init__(self, feishu):
        self._feishu = feishu

    def list_app_recommend_rule(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/application-v6/app_recommend_rule/list

        获取当前设置的推荐规则列表。
        """
        ...

    def underauditlist_application(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/application-v6/application/underauditlist

        查看本企业下所有待审核的自建应用列表
        """
        ...

    def get_application(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/application-v6/application/get

        根据app_id获取应用的基础信息
        """
        ...

    def get_application_app_version(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/application-v6/application-app_version/get

        根据 app_id，version_id 获取对应应用版本的信息
        """
        ...

    def list_application_app_version(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/application-v6/application-app_version/list

        根据 app_id 获取对应应用版本列表。
        """
        ...

    def patch_application_app_version(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/application-v6/application-app_version/patch

        通过接口来更新应用版本的审核结果：通过后应用可以直接上架；拒绝后则开发者可以看到拒绝理由，并在修改后再次申请发布。
        """
        ...

    def patch_application(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/application-v6/application/patch

        更新应用的分组信息（分组会影响应用在工作台中的分类情况，请谨慎更新）
        """
        ...

    def overview_application_app_usage(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/application-v6/application-app_usage/overview

        查看应用在某一天/某一周/某一个月的使用数据，可以查看租户整体对应用的使用情况，也可以分部门查看。
        """
        ...

    def patch_application_feedback(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/application-v6/application-feedback/patch

        更新应用的反馈数据
        """
        ...

    def list_application_feedback(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/application-v6/application-feedback/list

        查询应用的反馈数据
        """
        ...
