"""DO NOT EDIT THIS FILE!

This file is auto generated by feishu rest api description.
"""


from typing import TYPE_CHECKING, overload

from pydantic import BaseModel, parse_obj_as

if TYPE_CHECKING:
    from feishukit.response import Response


class CalendarClient:
    def __init__(self, feishu):
        self._feishu = feishu

    def primary_calendar(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar/primary

        获取当前身份的主日历信息。
        """
        ...

    def create_calendar(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar/create

        该接口用于为当前身份（应用 / 用户）创建一个共享日历。

        身份由 Header Authorization 的 Token 类型决定。
        """
        ...

    def delete_calendar(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar/delete

        该接口用于以当前身份（应用 / 用户）删除一个共享日历。

        身份由 Header Authorization 的 Token 类型决定。
        """
        ...

    def get_calendar(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar/get

        该接口用于以当前身份（应用 / 用户）根据日历 ID 获取日历信息。

        身份由 Header Authorization 的 Token 类型决定。
        """
        ...

    def list_calendar(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar/list

        该接口用于分页获得当前身份（应用 / 用户）的日历列表。

        身份由 Header Authorization 的 Token 类型决定。
        """
        ...

    def patch_calendar(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar/patch

        该接口用于以当前身份（应用 / 用户）修改日历信息。

        身份由 Header Authorization 的 Token 类型决定。
        """
        ...

    def search_calendar(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar/search

        该接口用于通过关键字查询公共日历或用户主日历。
        """
        ...

    def subscribe_calendar(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar/subscribe

        该接口用于以当前身份（应用 / 用户）订阅某个日历。

        身份由 Header Authorization 的 Token 类型决定。
        """
        ...

    def unsubscribe_calendar(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar/unsubscribe

        该接口用于以当前身份（应用 / 用户）取消对某日历的订阅状态。

        身份由 Header Authorization 的 Token 类型决定。
        """
        ...

    def subscription_calendar(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar/subscription

        该接口用于以用户身份订阅当前身份下日历列表中的所有日历变更。
        """
        ...

    def unsubscription_calendar(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar/unsubscription

        该接口用于以用户身份取消订阅当前身份下日历列表中的日历变更事件。
        """
        ...

    def create_calendar_acl(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-acl/create

        该接口用于以当前身份（应用 / 用户）给日历添加访问控制权限，即日历成员。

        身份由 Header Authorization 的 Token 类型决定。
        """
        ...

    def delete_calendar_acl(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-acl/delete

        该接口用于以当前身份（应用 / 用户）删除日历的控制权限，即日历成员。

        身份由 Header Authorization 的 Token 类型决定。
        """
        ...

    def list_calendar_acl(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-acl/list

        该接口用于以当前身份（应用 / 用户）获取日历的控制权限列表。

        身份由 Header Authorization 的 Token 类型决定。
        """
        ...

    def subscription_calendar_acl(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-acl/subscription

        该接口用于以用户身份订阅指定日历下的日历成员变更事件。
        """
        ...

    def unsubscription_calendar_acl(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-acl/unsubscription

        该接口用于以用户身份取消订阅指定日历下的日历成员变更事件。
        """
        ...

    def create_calendar_event(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-event/create

        该接口用于以当前身份（应用 / 用户）在日历上创建一个日程。

        身份由 Header Authorization 的 Token 类型决定。
        """
        ...

    def delete_calendar_event(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-event/delete

        该接口用于以当前身份（应用 / 用户）删除日历上的一个日程。

        身份由 Header Authorization 的 Token 类型决定。
        """
        ...

    def get_calendar_event(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-event/get

        该接口用于以当前身份（应用 / 用户）获取日历上的一个日程。
        身份由 Header Authorization 的 Token 类型决定。
        """
        ...

    def list_calendar_event(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-event/list

        该接口用于以当前身份（应用 / 用户）获取日历下的日程列表。
        身份由 Header Authorization 的 Token 类型决定。
        """
        ...

    def patch_calendar_event(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-event/patch

        该接口用于以当前身份（应用 / 用户）更新日历上的一个日程。

        身份由 Header Authorization 的 Token 类型决定。
        """
        ...

    def search_calendar_event(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-event/search

        该接口用于以用户身份搜索某日历下的相关日程。

        身份由 Header Authorization 的 Token 类型决定。
        """
        ...

    def subscription_calendar_event(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-event/subscription

        该接口用于以用户身份订阅指定日历下的日程变更事件。
        """
        ...

    def unsubscription_calendar_event(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-event/unsubscription

        该接口用于以用户身份取消订阅指定日历下的日程变更事件。
        """
        ...

    def create_calendar_event_attendee(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-event-attendee/create

        批量给日程添加参与人。
        """
        ...

    def list_calendar_event_attendee(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-event-attendee/list

        获取日程的参与人列表，若参与者列表中有群组，请使用 [获取参与人群成员列表](/ssl:ttdoc/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-event-attendee-chat_member/list) 。
        """
        ...

    def batch_delete_calendar_event_attendee(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-event-attendee/batch_delete

        批量删除日程的参与人。
        """
        ...

    def list_calendar_event_attendee_chat_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/calendar-event-attendee-chat_member/list

        获取日程的群参与人的群成员列表。
        """
        ...

    def list_freebusy(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/freebusy/list

        查询用户主日历或会议室的忙闲信息。
        """
        ...

    def create_timeoff_event(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/timeoff_event/create

        为指定用户创建一个请假日程，可以是一个普通请假日程，也可以是一个全天日程。
        创建请假日程后，会在相应时间内，在用户个人签名页展示请假信息。
        """
        ...

    def delete_timeoff_event(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/timeoff_event/delete

        删除一个指定的请假日程，请假日程删除，用户个人签名页的请假信息也会消失。
        一个应用只能删除自己创建的请假日程。
        """
        ...

    def generate_caldav_conf_setting(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/setting/generate_caldav_conf

        用于为当前用户生成一个CalDAV账号密码，用于将飞书日历信息同步到本地设备日历。
        """
        ...

    def create_exchange_binding(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/exchange_binding/create

        本接口将Exchange账户绑定到飞书账户，进而支持Exchange日历的导入
        """
        ...

    def get_exchange_binding(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/exchange_binding/get

        本接口获取Exchange账户的绑定状态，包括exchange日历是否同步完成。
        """
        ...

    def delete_exchange_binding(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/calendar-v4/exchange_binding/delete

        本接口解除Exchange账户和飞书账户的绑定关系，Exchange账户解除绑定后才能绑定其他飞书账户
        """
        ...
