"""DO NOT EDIT THIS FILE!

This file is auto generated by feishu rest api description.
"""


from typing import TYPE_CHECKING, overload

from pydantic import BaseModel, parse_obj_as

if TYPE_CHECKING:
    from feishukit.response import Response


class CcmClient:
    def __init__(self, feishu):
        self._feishu = feishu

    def list_file(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file/list

        获取用户云空间中指定文件夹下的文件清单。清单类型包括文件、各种在线文档（文档、电子表格、多维表格、思维笔记）、文件夹和快捷方式。该接口支持分页，但是不会递归的获取子文件夹的清单。
        """
        ...

    def create_folder_file(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file/create_folder

        在用户云空间的指定文件夹中创建一个新的空文件夹。
        """
        ...

    def batch_query_meta(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/meta/batch_query

        该接口用于根据 token 获取各类文件的元数据
        """
        ...

    def copy_file(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file/copy

        将文件复制到用户云空间的其他文件夹中。不支持复制文件夹。

        如果目标文件夹是我的空间，则复制的文件会在「**我的空间**」的「**归我所有**」列表里。
        """
        ...

    def move_file(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file/move

        将文件或者文件夹移动到用户云空间的其他位置。
        """
        ...

    def delete_file(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file/delete

        删除用户在云空间内的文件或者文件夹。文件或者文件夹被删除后，会进入用户回收站里。
        """
        ...

    def get_file_statistics(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file-statistics/get

        此接口用于获取文件统计信息，包括文档阅读人数、次数和点赞数。
        """
        ...

    def task_check_file(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file/task_check

        查询删除文件夹等异步任务的状态信息。
        """
        ...

    def upload_all_media(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/media/upload_all

        将文件、图片、视频等素材文件上传到指定云文档中。素材文件在云空间中不会显示，只会显示在对应云文档中。
        """
        ...

    def download_media(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/media/download

        使用该接口可以下载素材。素材表示在各种创作容器里的文件，如Doc文档内的图片，文件均属于素材。支持range下载。
        """
        ...

    def batch_get_tmp_download_url_media(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/media/batch_get_tmp_download_url

        通过file_token获取素材临时下载链接，链接时效性是24小时，过期失效。
        """
        ...

    def upload_prepare_media(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/media/upload_prepare

        发送初始化请求获取上传事务ID和分块策略，目前是以4MB大小进行定长分片。
        """
        ...

    def upload_part_media(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/media/upload_part

        上传对应的文件块。
        """
        ...

    def upload_finish_media(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/media/upload_finish

        触发完成上传。
        """
        ...

    def subscribe_file(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file/subscribe

        该接口仅支持**文档拥有者**订阅自己文档的通知事件，可订阅的文档类型为**旧版文档**、**新版文档**、**电子表格**和**多维表格**。在调用该接口之前请确保正确[配置事件回调网址和订阅事件类型](/ssl:ttdoc/ukTMukTMukTM/uUTNz4SN1MjL1UzM#2eb3504a)，事件类型参考[事件列表](/ssl:ttdoc/ukTMukTMukTM/uYDNxYjL2QTM24iN0EjN/event-list)。
        """
        ...

    def upload_all_file(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file/upload_all

        向云空间指定目录下上传一个小文件。
        """
        ...

    def upload_prepare_file(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file/upload_prepare

        发送初始化请求获取上传事务ID和分块策略，目前是以4MB大小进行定长分片。
        """
        ...

    def upload_part_file(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file/upload_part

        上传对应的文件块。
        """
        ...

    def upload_finish_file(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file/upload_finish

        触发完成上传。
        """
        ...

    def download_file(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file/download

        使用该接口可以下载在云空间目录下的文件（不含飞书文档/表格/思维导图等在线文档）。支持range下载。
        """
        ...

    def create_import_task(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/import_task/create

        创建导入任务。支持导入为 doc、docx、sheet、bitable，参考[导入用户指南](/ssl:ttdoc/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/import_task/import-user-guide)
        """
        ...

    def get_import_task(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/import_task/get

        根据创建导入任务返回的 ticket 查询导入结果。
        """
        ...

    def create_export_task(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/export_task/create

        创建导出任务，将云文件导出为指定格式的本地文件。该接口为异步接口，需要通过轮询 [查询导出任务结果](/ssl:ttdoc/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/export_task/get) 接口获取任务结果。
        """
        ...

    def get_export_task(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/export_task/get

        根据[创建导出任务](/ssl::ttdoc//uAjLw4CM/ukTMukTMukTM/reference/drive-v1/export_task/create)的ticket查询导出任务的结果，前提条件需要先调用创建导出任务接口。

        通过该接口获取到下载文件的 token 后调用[下载导出文件接口](/ssl::ttdoc//uAjLw4CM/ukTMukTMukTM/reference/drive-v1/export_task/download)将文件进行下载
        """
        ...

    def download_export_task(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/export_task/download

        根据任务导出结果的token，下载导出文件
        """
        ...

    def list_permission_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/permission-member/list

        该接口用于根据 filetoken 查询协作者
        """
        ...

    def create_permission_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/permission-member/create

        该接口用于根据 filetoken 给用户增加文档的权限。
        """
        ...

    def update_permission_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/permission-member/update

        该接口用于根据 filetoken 更新文档协作者的权限。
        """
        ...

    def delete_permission_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/permission-member/delete

        该接口用于根据 filetoken 移除文档协作者的权限。
        """
        ...

    def get_permission_public(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/permission-public/get

        该接口用于根据 filetoken 获取云文档的权限设置。
        """
        ...

    def patch_permission_public(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/permission-public/patch

        该接口用于根据 filetoken 更新云文档的权限设置。
        """
        ...

    def list_file_comment(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file-comment/list

        该接口用于根据文档 token 分页获取文档评论。
        """
        ...

    def create_file_comment(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file-comment/create

        往云文档添加一条全局评论。
        """
        ...

    def get_file_comment(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file-comment/get

        获取云文档中的某条评论。
        """
        ...

    def update_file_comment_reply(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file-comment-reply/update

        更新云文档中的某条回复。
        """
        ...

    def delete_file_comment_reply(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file-comment-reply/delete

        删除云文档中的某条回复。
        """
        ...

    def patch_file_comment(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file-comment/patch

        解决或恢复云文档中的评论。
        """
        ...

    def get_document(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/document-docx/docx-v1/document/get

        获取文档最新版本号、标题等
        """
        ...

    def raw_content_document(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/document-docx/docx-v1/document/raw_content

        获取文档的纯文本内容。
        """
        ...

    def list_document_block(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/document-docx/docx-v1/document-block/list

        获取文档所有块的富文本内容并分页返回。
        """
        ...

    def create_document(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/document-docx/docx-v1/document/create

        创建新版文档，文档标题和目录可选。
        """
        ...

    def get_document_block(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/document-docx/docx-v1/document-block/get

        获取指定块的富文本内容。
        """
        ...

    def create_document_block_children(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/document-docx/docx-v1/document-block-children/create

        指定需要操作的块，为其创建一批子块，并插入到指定位置。如果操作成功，接口将返回新创建子块的富文本内容。
        """
        ...

    def patch_document_block(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/document-docx/docx-v1/document-block/patch

        更新指定的块。
        """
        ...

    def batch_update_document_block(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/document-docx/docx-v1/document-block/batch_update

        批量更新块的富文本内容。
        """
        ...

    def batch_delete_document_block_children(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/document-docx/docx-v1/document-block-children/batch_delete

        指定需要操作的块，删除其指定范围的子块。如果操作成功，接口将返回应用删除操作后的文档版本号。
        """
        ...

    def get_document_block_children(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/document-docx/docx-v1/document-block-children/get

        给定一个指定版本的文档，并指定需要操作的块，分页遍历其所有子块富文本内容 。如果不指定版本，则会默认查询最新版本。
        """
        ...

    def patch_spreadsheet(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet/patch

        该接口用于修改电子表格的属性
        """
        ...

    def get_spreadsheet(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet/get

        该接口用于获取电子表格的基础信息。
        """
        ...

    def create_spreadsheet(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet/create

        在指定目录下创建表格
        """
        ...

    def get_spreadsheet_sheet(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet/get

        该接口用于通过工作表ID查询工作表属性信息。
        """
        ...

    def query_spreadsheet_sheet(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet/query

        该接口用于获取电子表格下所有工作表及其属性。
        """
        ...

    def move_dimension_spreadsheet_sheet(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet/move_dimension

        该接口用于移动行列，行列被移动到目标位置后，原本在目标位置的行列会对应右移或下移。
        """
        ...

    def find_spreadsheet_sheet(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet/find

        在指定范围内查找符合查找条件的单元格。
        """
        ...

    def replace_spreadsheet_sheet(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet/replace

        按照指定的条件查找子表的某个范围内的数据符合条件的单元格并替换值，返回替换成功的单元格位置。一次请求最多允许替换5000个单元格，如果超过请将range缩小范围再操作。请求体中的 range、find、replaccement 字段必填。
        """
        ...

    def get_spreadsheet_sheet_filter(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter/get

        获取子表的详细筛选信息
        """
        ...

    def create_spreadsheet_sheet_filter(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter/create

        在子表内创建筛选。
        """
        ...

    def update_spreadsheet_sheet_filter(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter/update

        更新子表筛选范围中的列筛选条件。
        """
        ...

    def delete_spreadsheet_sheet_filter(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter/delete

        删除子表的筛选
        """
        ...

    def get_spreadsheet_sheet_filter_view(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter_view/get

        获取指定筛选视图 id 的名字和筛选范围。
        """
        ...

    def query_spreadsheet_sheet_filter_view(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter_view/query

        查询子表内所有的筛选视图基本信息，包括 id、name 和 range
        """
        ...

    def create_spreadsheet_sheet_filter_view(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter_view/create

        根据传入的参数创建一个筛选视图。Id 和 名字可选，不填的话会默认生成；range 必填。Id 长度为10，由 0-9、a-z、A-Z 组合生成。名字长度不超过100。单个子表内的筛选视图个数不超过 150。
        """
        ...

    def patch_spreadsheet_sheet_filter_view(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter_view/patch

        更新筛选视图的名字或者筛选范围。名字长度不超过100，不能重复即子表内唯一；筛选范围不超过子表的最大范围。
        """
        ...

    def delete_spreadsheet_sheet_filter_view(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter_view/delete

        删除指定 id 对应的筛选视图。
        """
        ...

    def get_spreadsheet_sheet_filter_view_condition(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter_view-condition/get

        获取筛选视图某列的筛选条件信息。
        """
        ...

    def query_spreadsheet_sheet_filter_view_condition(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter_view-condition/query

        查询一个筛选视图的所有筛选条件，返回筛选视图的筛选范围内的筛选条件。
        """
        ...

    def create_spreadsheet_sheet_filter_view_condition(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter_view-condition/create

        在筛选视图的筛选范围的某一列创建筛选条件。
        """
        ...

    def update_spreadsheet_sheet_filter_view_condition(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter_view-condition/update

        更新筛选视图范围的某列的筛选条件，condition id 即为列的字母号。
        """
        ...

    def delete_spreadsheet_sheet_filter_view_condition(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-filter_view-condition/delete

        删除筛选视图的筛选范围某一列的筛选条件。
        """
        ...

    def get_spreadsheet_sheet_float_image(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-float_image/get

        根据 float_image_id 获取对应浮动图片的信息。
        """
        ...

    def query_spreadsheet_sheet_float_image(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-float_image/query

        返回子表内所有的浮动图片信息。
        """
        ...

    def create_spreadsheet_sheet_float_image(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-float_image/create

        根据传入的参数创建一张浮动图片。Float_image_token （[上传图片至表格后得到](/ssl:ttdoc/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/media/upload_all)）和range（只支持一个单元格） 必填。Float_image_id 可选，不填的话会默认生成，长度为10，由 0-9、a-z、A-Z 组合生成。表格内不重复的图片（浮动图片+单元格图片）总数不超过4000。width 和 height 为图片展示的宽高，可选，不填的话会使用图片的真实宽高。offset_x 和 offset_y 为图片左上角距离所在单元格左上角的偏移，可选，默认为 0。
        """
        ...

    def patch_spreadsheet_sheet_float_image(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-float_image/patch

        更新已有的浮动图片位置和宽高，包括 range、width、height、offset_x 和 offset_y，不包括 float_image_id 和 float_image_token。
        """
        ...

    def delete_spreadsheet_sheet_float_image(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet-float_image/delete

        删除 float_image_id 对应的浮动图片。
        """
        ...

    def get_app(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app/get

        获取指定多维表格的元数据信息，包括多维表格名称，多维表格版本号，多维表格是否开启高级权限等。
        """
        ...

    def update_app(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app/update

        通过 app_token 更新多维表格元数据
        """
        ...

    def list_app_table(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table/list

        根据  app_token，获取多维表格下的所有数据表
        """
        ...

    def create_app_table(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table/create

        新增一个数据表
        """
        ...

    def delete_app_table(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table/delete

        删除一个数据表
        """
        ...

    def batch_create_app_table(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table/batch_create

        新增多个数据表
        """
        ...

    def batch_delete_app_table(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table/batch_delete

        删除多个数据表
        """
        ...

    def list_app_dashboard(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-dashboard/list

        根据 app_token，获取多维表格下的所有仪表盘
        """
        ...

    def list_app_table_view(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-view/list

        根据 app_token 和 table_id，获取数据表的所有视图
        """
        ...

    def create_app_table_view(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-view/create

        在数据表中新增一个视图
        """
        ...

    def delete_app_table_view(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-view/delete

        删除数据表中的视图
        """
        ...

    def patch_app_table_form(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-form/patch

        该接口用于更新表单中的元数据项
        """
        ...

    def get_app_table_form(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-form/get

        获取表单的所有元数据项
        """
        ...

    def patch_app_table_form_field(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-form-field/patch

        该接口用于更新表单中的问题项
        """
        ...

    def list_app_table_form_field(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-form-field/list

        列出表单的所有问题项
        """
        ...

    def get_app_table_record(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-record/get

        该接口用于根据 record_id 的值检索现有记录
        """
        ...

    def list_app_table_record(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-record/list

        该接口用于列出数据表中的现有记录，单次最多列出 500 行记录，支持分页获取。
        """
        ...

    def create_app_table_record(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-record/create

        该接口用于在数据表中新增一条记录
        """
        ...

    def update_app_table_record(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-record/update

        该接口用于更新数据表中的一条记录
        """
        ...

    def delete_app_table_record(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-record/delete

        该接口用于删除数据表中的一条记录
        """
        ...

    def batch_create_app_table_record(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-record/batch_create

        该接口用于在数据表中新增多条记录，单次调用最多新增 500 条记录。
        """
        ...

    def batch_update_app_table_record(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-record/batch_update

        该接口用于更新数据表中的多条记录，单次调用最多更新 500 条记录。
        """
        ...

    def batch_delete_app_table_record(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-record/batch_delete

        该接口用于删除数据表中现有的多条记录，单次调用中最多删除 500 条记录。
        """
        ...

    def list_app_table_field(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-field/list

        根据 app_token 和 table_id，获取数据表的所有字段
        """
        ...

    def create_app_table_field(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-field/create

        该接口用于在数据表中新增一个字段
        """
        ...

    def update_app_table_field(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-field/update

        该接口用于在数据表中更新一个字段
        """
        ...

    def delete_app_table_field(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-table-field/delete

        该接口用于在数据表中删除一个字段
        """
        ...

    def list_app_role(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-role/list

        列出自定义角色
        """
        ...

    def create_app_role(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-role/create

        新增自定义角色
        """
        ...

    def delete_app_role(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-role/delete

        删除自定义角色
        """
        ...

    def update_app_role(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-role/update

        更新自定义角色
        """
        ...

    def batch_delete_app_role_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-role-member/batch_delete

        批量删除自定义角色的协作者
        """
        ...

    def batch_create_app_role_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-role-member/batch_create

        批量新增自定义角色的协作者
        """
        ...

    def list_app_role_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-role-member/list

        列出自定义角色的协作者
        """
        ...

    def create_app_role_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-role-member/create

        新增自定义角色的协作者
        """
        ...

    def delete_app_role_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app-role-member/delete

        删除自定义角色的协作者
        """
        ...

    def list_space(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-v2/space/list

        此接口用于获取有权限访问的知识空间列表。

        此接口为分页接口。由于权限过滤，可能返回列表为空，但分页标记（has_more）为true，可以继续分页请求。

        对于知识空间各项属性描述请参阅[获取知识空间信息](/ssl:ttdoc/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-v2/space/get)
        """
        ...

    def get_space(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-v2/space/get

        此接口用于根据知识空间ID来查询知识空间的信息。

        空间类型（type）：
        - 个人空间：归个人管理。一人仅可拥有一个个人空间，无法添加其他管理员。
        - 团队空间：归团队（多人)管理，可添加多个管理员。

        空间可见性（visibility）：
        - 公开空间：租户所有用户可见，默认为成员权限。无法额外添加成员，但可以添加管理员。
        - 私有空间：仅对知识空间管理员、成员可见，需要手动添加管理员、成员。
        """
        ...

    def create_space(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-v2/space/create

        此接口用于创建知识空间
        """
        ...

    def create_space_member(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-v2/space-member/create

        添加知识空间成员或管理员。
        """
        ...

    def delete_space_member(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-v2/space-member/delete

        此接口用于删除知识空间成员或管理员。
        """
        ...

    def update_space_setting(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-v2/space-setting/update

        根据space_id更新知识空间公共设置
        """
        ...

    def create_space_node(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-v2/space-node/create

        此接口用于在知识节点里创建[节点](/ssl:ttdoc/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-overview)到指定位置。
        """
        ...

    def get_node_space(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-v2/space/get_node

        获取知识空间节点信息
        """
        ...

    def list_space_node(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-v2/space-node/list

        此接口用于分页获取Wiki节点的子节点列表。

        此接口为分页接口。由于权限过滤，可能返回列表为空，但分页标记（has_more）为true，可以继续分页请求。
        """
        ...

    def move_space_node(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-v2/space-node/move

        此方法用于在Wiki内移动节点，支持跨知识空间移动。如果有子节点，会携带子节点一起移动。
        """
        ...

    def update_title_space_node(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-v2/space-node/update_title

        此接口用于更新节点标题
        """
        ...

    def copy_space_node(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-v2/space-node/copy

        此接口用于在知识空间创建节点副本到指定位置。
        """
        ...

    def move_docs_to_wiki_space_node(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-v2/space-node/move_docs_to_wiki

        该接口允许移动云空间文档至知识空间，并挂载在指定位置
        """
        ...

    def get_task(
        self,
    ):
        """
        https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-v2/task/get

        该方法用于获取wiki异步任务的结果
        """
        ...

    def get_file_subscription(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file-subscription/get

        根据订阅ID获取该订阅的状态
        """
        ...

    def create_file_subscription(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file-subscription/create

        订阅文档中的变更事件，当前支持文档评论订阅，订阅后文档评论更新会有“云文档助手”推送给订阅的用户
        """
        ...

    def patch_file_subscription(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file-subscription/patch

        根据订阅ID更新订阅状态
        """
        ...
