"""DO NOT EDIT THIS FILE!

This file is auto generated by feishu rest api description.
"""


from typing import TYPE_CHECKING, overload

from pydantic import BaseModel, parse_obj_as

if TYPE_CHECKING:
    from feishukit.response import Response


class HelpdeskClient:
    def __init__(self, feishu):
        self._feishu = feishu

    def create_notification(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/notification/create

        调用接口创建推送，创建成功后为草稿状态
        """
        ...

    def patch_notification(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/notification/patch

        更新推送信息，只有在草稿状态下才可以调用此接口进行更新
        """
        ...

    def get_notification(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/notification/get

        查询推送详情
        """
        ...

    def preview_notification(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/notification/preview

        在正式执行推送之前是可以调用此接口预览设置的推送内容
        """
        ...

    def submit_approve_notification(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/notification/submit_approve

        正常情况下调用创建推送接口后，就可以调用提交审核接口，如果创建人是服务台owner则会自动审核通过，否则会通知服务台owner审核此推送信息
        """
        ...

    def cancel_approve_notification(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/notification/cancel_approve

        提交审核后，如果需要取消审核，则调用此接口
        """
        ...

    def execute_send_notification(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/notification/execute_send

        审核通过后调用此接口设置推送时间，等待调度系统调度，发送消息
        """
        ...

    def cancel_send_notification(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/notification/cancel_send

        取消推送接口，审核通过后待调度可以调用，发送过程中可以调用（会撤回已发送的消息），发送完成后可以需要推送（会撤回所有已发送的消息）
        """
        ...

    def start_service_ticket(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/ticket/start_service

        该接口用于创建服务台对话。
        """
        ...

    def get_ticket(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/ticket/get

        该接口用于获取单个服务台工单详情。仅支持自建应用。
        """
        ...

    def update_ticket(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/ticket/update

        该接口用于更新服务台工单详情。只会更新数据，不会触发相关操作。如修改工单状态到关单，不会关闭聊天页面。仅支持自建应用。要更新的工单字段必须至少输入一项。
        """
        ...

    def list_ticket(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/ticket/list

        该接口用于获取全部工单详情。仅支持自建应用。
        """
        ...

    def ticket_image_ticket(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/ticket/ticket_image

        该接口用于获取服务台工单消息图象。仅支持自建应用。
        """
        ...

    def answer_user_query_ticket(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/ticket/answer_user_query

        该接口用于回复用户提问结果至工单，需要工单仍处于进行中且未接入人工状态。仅支持自建应用。
        """
        ...

    def customized_fields_ticket(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/ticket/customized_fields

        该接口用于获取服务台自定义字段详情。
        """
        ...

    def create_ticket_message(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/ticket-message/create

        该接口用于工单发送消息。
        """
        ...

    def list_ticket_message(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/ticket-message/list

        该接口用于获取服务台工单消息详情。
        """
        ...

    def create_bot_message(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/bot-message/create

        通过服务台机器人给指定用户的服务台专属群或私聊发送消息，支持文本、富文本、卡片、图片。
        """
        ...

    def list_ticket_customized_field(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/ticket_customized_field/list-ticket-customized-fields

        该接口用于获取全部工单自定义字段。
        """
        ...

    def delete_ticket_customized_field(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/ticket_customized_field/delete

        该接口用于删除工单自定义字段。
        """
        ...

    def patch_ticket_customized_field(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/ticket_customized_field/update-ticket-customized-field

        该接口用于更新自定义字段。
        """
        ...

    def create_ticket_customized_field(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/ticket_customized_field/create-ticket-customized-field

        该接口用于创建自定义字段
        """
        ...

    def get_ticket_customized_field(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/ticket_customized_field/get-ticket-customized-field

        该接口用于获取工单自定义字段详情。
        """
        ...

    def create_category(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/category/create

        该接口用于创建知识库分类。
        """
        ...

    def get_category(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/category/get

        该接口用于获取知识库分类。
        """
        ...

    def patch_category(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/category/patch

        该接口用于更新知识库分类详情。
        """
        ...

    def delete_category(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/category/delete

        该接口用于删除知识库分类详情。
        """
        ...

    def list_category(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/category/list-categories

        该接口用于获取服务台知识库所有分类
        """
        ...

    def create_faq(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/faq/create

        该接口用于创建知识库。
        """
        ...

    def get_faq(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/faq/get

        该接口用于获取服务台知识库详情。
        """
        ...

    def patch_faq(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/faq/patch

        该接口用于修改知识库。
        """
        ...

    def delete_faq(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/faq/delete

        该接口用于删除知识库。
        """
        ...

    def list_faq(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/faq/list

        该接口用于获取服务台知识库详情。
        """
        ...

    def faq_image_faq(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/faq/faq_image

        该接口用于获取知识库图像。
        """
        ...

    def search_faq(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/faq/search

        该接口用于搜索服务台知识库。
        """
        ...

    def patch_agent(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/agent/patch

        更新客服状态等信息
        """
        ...

    def agent_email_agent(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/agent/agent_email

        该接口用于获取客服邮箱地址
        """
        ...

    def create_agent_schedule(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/agent_schedule/create

        该接口用于创建客服
        """
        ...

    def delete_agent_schedules(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/agent-schedules/delete

        该接口用于删除客服
        """
        ...

    def patch_agent_schedules(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/agent-schedules/patch

        该接口用于更新客服的日程
        """
        ...

    def get_agent_schedules(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/agent-schedules/get

        该接口用于获取客服信息
        """
        ...

    def list_agent_schedule(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/agent_schedule/list

        该接口用于获取所有客服信息
        """
        ...

    def create_agent_skill(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/agent_skill/create

        该接口用于创建客服技能
        """
        ...

    def patch_agent_skill(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/agent_skill/patch

        该接口用于更新客服技能
        """
        ...

    def delete_agent_skill(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/agent_skill/delete

        该接口用于删除客服技能
        """
        ...

    def get_agent_skill(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/agent_skill/get

        该接口用于获取客服技能
        """
        ...

    def list_agent_skill(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/agent_skill/list

        获取全部客服技能
        """
        ...

    def list_agent_skill_rule(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/agent_skill_rule/list

        该接口用于获取全部客服技能。仅支持自建应用。
        """
        ...

    def subscribe_event(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/event/subscribe

        用于订阅服务台事件
        """
        ...

    def unsubscribe_event(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/helpdesk-v1/event/unsubscribe

        用于取消订阅服务台事件
        """
        ...
