"""DO NOT EDIT THIS FILE!

This file is auto generated by feishu rest api description.
"""


from typing import TYPE_CHECKING, overload

from pydantic import BaseModel, parse_obj_as

if TYPE_CHECKING:
    from feishukit.response import Response


class ImClient:
    def __init__(self, feishu):
        self._feishu = feishu

    def create_message(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/create

        给指定用户或者会话发送消息，支持文本、富文本、可交互的[消息卡片](/ssl:ttdoc/ukTMukTMukTM/uczM3QjL3MzN04yNzcDN)、群名片、个人名片、图片、视频、音频、文件、表情包。
        """
        ...

    def reply_message(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/reply

        回复指定消息，支持文本、富文本、卡片、群名片、个人名片、图片、视频、文件等多种消息类型。
        """
        ...

    def delete_message(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/delete

        机器人撤回机器人自己发送的消息或群主撤回群内消息。
        """
        ...

    def read_users_message(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/read_users

        查询消息的已读信息。
        """
        ...

    def list_message(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/list

        获取会话（包括单聊、群组）的历史消息（聊天记录）。
        """
        ...

    def get_message_resource(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message-resource/get

        获取消息中的资源文件，包括音频，视频，图片和文件，**暂不支持表情包资源下载**。当前仅支持 100M 以内的资源文件的下载。
        """
        ...

    def get_message(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/get

        通过 message_id 查询消息内容。
        """
        ...

    def urgent_app_message(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/urgent_app

        对指定消息进行应用内加急。
        """
        ...

    def urgent_sms_message(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/urgent_sms

        对指定消息进行应用内加急与短信加急。
        """
        ...

    def urgent_phone_message(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/urgent_phone

        对指定消息进行应用内加急与电话加急。
        """
        ...

    def delete_batch_message(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/batch_message/delete

        批量撤回通过[批量发送消息](/ssl:ttdoc/ukTMukTMukTM/ucDO1EjL3gTNx4yN4UTM)接口发送的消息。
        """
        ...

    def read_user_batch_message(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/batch_message/read_user

        批量发送消息后，可以通过该接口查询批量消息推送的总人数和阅读人数。
        """
        ...

    def get_progress_batch_message(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/batch_message/get_progress

        该接口在[查询批量消息推送和阅读人数](/ssl:ttdoc/uAjLw4CM/ukTMukTMukTM/reference/im-v1/batch_message/read_user)查询结果的基础上，增加了批量请求中有效的userid数量以及消息撤回进度数据。
        """
        ...

    def create_image(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/image/create

        上传图片接口，支持上传 JPEG、PNG、WEBP、GIF、TIFF、BMP、ICO格式图片。
        """
        ...

    def get_image(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/image/get

        下载图片资源，只能下载当前应用所上传且图片类型为message的图片。
        """
        ...

    def create_file(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/file/create

        上传文件，可以上传视频，音频和常见的文件类型。
        """
        ...

    def get_file(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/file/get

        下载文件接口，只能下载应用自己上传的文件。
        """
        ...

    def patch_message(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/patch

        更新应用已发送的消息卡片内容。
        """
        ...

    def create_message_reaction(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message-reaction/create

        给指定消息添加指定类型的表情回复（reaction即表情回复，本文档统一用“reaction”代称）。
        """
        ...

    def list_message_reaction(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message-reaction/list

        获取指定消息的特定类型表情回复列表（reaction即表情回复，本文档统一用“reaction”代称）。
        """
        ...

    def delete_message_reaction(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message-reaction/delete

        删除指定消息的表情回复（reaction即表情回复，本文档统一用“reaction”代称）。
        """
        ...

    def create_pin(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/pin/create

        Pin一条指定的消息。
        """
        ...

    def delete_pin(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/pin/delete

        移除一条指定消息的Pin。
        """
        ...

    def list_pin(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/pin/list

        获取所在群内指定时间范围内的所有Pin消息。
        """
        ...

    def create_chat(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat/create

        创建群并设置群头像、群名、群描述等。
        """
        ...

    def get_chat(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat/get

        获取群名称、群描述、群头像、群主 ID 等群基本信息。
        """
        ...

    def update_chat(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat/update

        更新群头像、群名称、群描述、群配置、转让群主等。
        """
        ...

    def delete_chat(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat/delete

        解散群组。
        """
        ...

    def list_chat(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat/list

        获取用户或者机器人所在群列表。
        """
        ...

    def search_chat(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat/search

        搜索对用户或机器人可见的群列表，包括：用户或机器人所在的群、对用户或机器人公开的群。
        搜索可获得的群信息包括：群ID（chat_id）、群名称、群描述等。
        """
        ...

    def get_chat_moderation(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-moderation/get

        获取群发言模式、可发言用户名单等
        """
        ...

    def update_chat_moderation(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-moderation/update

        更新群组的发言权限设置，可设置为全员可发言、仅管理员可发言  或 指定用户可发言。
        """
        ...

    def put_top_notice_chat_top_notice(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-top_notice/put_top_notice

        更新会话中的群置顶信息，可以将群中的某一条消息，或者群公告置顶显示。
        """
        ...

    def delete_top_notice_chat_top_notice(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-top_notice/delete_top_notice

        撤销会话中的置顶。
        """
        ...

    def link_chat(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat/link

        获取指定群的分享链接。
        """
        ...

    def create_chat_members(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-members/create

        将用户或机器人拉入群聊。
        """
        ...

    def delete_chat_members(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-members/delete

        将用户或机器人移出群聊。
        """
        ...

    def me_join_chat_members(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-members/me_join

        用户或机器人主动加入群聊。
        """
        ...

    def get_chat_members(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-members/get

        获取用户/机器人所在群的群成员列表。
        """
        ...

    def is_in_chat_chat_members(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-members/is_in_chat

        根据使用的access_token判断对应的用户或者机器人是否在群里。
        """
        ...

    def add_managers_chat_managers(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-managers/add_managers

        将用户或机器人指定为群管理员。
        """
        ...

    def delete_managers_chat_managers(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-managers/delete_managers

        删除指定的群管理员（用户或机器人）。
        """
        ...

    def get_chat_announcement(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-announcement/get

        获取会话中的群公告信息，公告信息格式与[云文档](https://open.feishu.cn/document/ukTMukTMukTM/uAzM5YjLwMTO24CMzkjN)格式相同。
        """
        ...

    def patch_chat_announcement(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-announcement/patch

        更新会话中的群公告信息，更新公告信息的格式和更新[云文档](https://open.feishu.cn/document/ukTMukTMukTM/uAzM5YjLwMTO24CMzkjN)格式相同。
        """
        ...

    def create_chat_tab(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-tab/create

        添加自定义会话标签页。
        """
        ...

    def delete_tabs_chat_tab(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-tab/delete_tabs

        删除会话标签页。
        """
        ...

    def list_tabs_chat_tab(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-tab/list_tabs

        拉取会话标签页。
        """
        ...

    def update_tabs_chat_tab(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-tab/update_tabs

        更新会话标签页
        """
        ...

    def sort_tabs_chat_tab(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-tab/sort_tabs

        会话标签页排序。
        """
        ...
