"""DO NOT EDIT THIS FILE!

This file is auto generated by feishu rest api description.
"""


from typing import TYPE_CHECKING, overload

from pydantic import BaseModel, parse_obj_as

if TYPE_CHECKING:
    from feishukit.response import Response


class MailClient:
    def __init__(self, feishu):
        self._feishu = feishu

    def create_mailgroup(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup/create

        创建一个邮件组
        """
        ...

    def get_mailgroup(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup/get

        获取特定邮件组信息
        """
        ...

    def list_mailgroup(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup/list

        分页批量获取邮件组
        """
        ...

    def patch_mailgroup(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup/patch

        更新邮件组部分字段，没有填写的字段不会被更新
        """
        ...

    def update_mailgroup(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup/update

        更新邮件组所有信息
        """
        ...

    def delete_mailgroup(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup/delete

        删除一个邮件组
        """
        ...

    def create_mailgroup_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup-member/create

        向邮件组添加单个成员
        """
        ...

    def get_mailgroup_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup-member/get

        获取邮件组单个成员信息
        """
        ...

    def list_mailgroup_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup-member/list

        分页批量获取邮件组成员列表
        """
        ...

    def delete_mailgroup_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup-member/delete

        删除邮件组单个成员
        """
        ...

    def create_mailgroup_permission_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup-permission_member/create

        向邮件组添加单个自定义权限成员，添加后该成员可发送邮件到该邮件组
        """
        ...

    def get_mailgroup_permission_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup-permission_member/get

        获取邮件组单个权限成员信息
        """
        ...

    def list_mailgroup_permission_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup-permission_member/list

        分页批量获取邮件组权限成员列表
        """
        ...

    def delete_mailgroup_permission_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup-permission_member/delete

        从自定义成员中删除单个成员，删除后该成员无法发送邮件到该邮件组
        """
        ...

    def create_mailgroup_alias(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup-alias/create

        创建邮件组别名
        """
        ...

    def list_mailgroup_alias(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup-alias/list

        获取邮件组所有别名
        """
        ...

    def delete_mailgroup_alias(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/mailgroup-alias/delete

        删除邮件组别名
        """
        ...

    def create_public_mailbox(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/public_mailbox/create

        创建一个公共邮箱
        """
        ...

    def get_public_mailbox(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/public_mailbox/get

        获取公共邮箱信息
        """
        ...

    def list_public_mailbox(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/public_mailbox/list

        分页批量获取公共邮箱列表
        """
        ...

    def patch_public_mailbox(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/public_mailbox/patch

        更新公共邮箱部分字段，没有填写的字段不会被更新
        """
        ...

    def update_public_mailbox(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/public_mailbox/update

        更新公共邮箱所有信息
        """
        ...

    def delete_public_mailbox(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/public_mailbox/delete

        该接口会永久删除公共邮箱地址。可用于释放邮箱回收站的公共邮箱地址，一旦删除，该邮箱地址将无法恢复。
        """
        ...

    def create_public_mailbox_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/public_mailbox-member/create

        向公共邮箱添加单个成员
        """
        ...

    def get_public_mailbox_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/public_mailbox-member/get

        获取公共邮箱单个成员信息
        """
        ...

    def list_public_mailbox_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/public_mailbox-member/list

        分页批量获取公共邮箱成员列表
        """
        ...

    def delete_public_mailbox_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/public_mailbox-member/delete

        删除公共邮箱单个成员
        """
        ...

    def clear_public_mailbox_member(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/public_mailbox-member/clear

        删除公共邮箱所有成员
        """
        ...

    def create_public_mailbox_alias(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/public_mailbox-alias/create

        创建公共邮箱别名
        """
        ...

    def list_public_mailbox_alias(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/public_mailbox-alias/list

        获取所有公共邮箱别名
        """
        ...

    def delete_public_mailbox_alias(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/public_mailbox-alias/delete

        删除公共邮箱别名
        """
        ...

    def delete_user_mailbox(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/user_mailbox/delete

        该接口会永久删除用户邮箱地址。可用于删除位于邮箱回收站中的用户邮箱地址，一旦删除，将无法恢复。该接口支持邮件的转移，可以将被释放邮箱的邮件转移到另外一个可以使用的邮箱中。
        """
        ...

    def create_user_mailbox_alias(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/user_mailbox-alias/create

        创建用户邮箱别名
        """
        ...

    def list_user_mailbox_alias(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/user_mailbox-alias/list

        获取用户邮箱所有别名
        """
        ...

    def delete_user_mailbox_alias(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/user_mailbox-alias/delete

        删除用户邮箱别名
        """
        ...

    def query_user(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/mail-v1/user/query

        使用邮箱状态查询接口，可以输入邮箱地址，查询出该邮箱地址对应的类型以及状态
        """
        ...
