"""DO NOT EDIT THIS FILE!

This file is auto generated by feishu rest api description.
"""


from typing import TYPE_CHECKING, overload

from pydantic import BaseModel, parse_obj_as

if TYPE_CHECKING:
    from feishukit.response import Response


class PassportClient:
    def __init__(self, feishu):
        self._feishu = feishu

    def query_session(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/passport-v1/session/query

        该接口用于查询用户的登录信息
        """
        ...
