"""DO NOT EDIT THIS FILE!

This file is auto generated by feishu rest api description.
"""


from typing import TYPE_CHECKING, overload

from pydantic import BaseModel, parse_obj_as

if TYPE_CHECKING:
    from feishukit.response import Response


class TaskClient:
    def __init__(self, feishu):
        self._feishu = feishu

    def create_task(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task/create

        该接口可以创建一个任务，支持填写任务的基本信息，包括任务的标题，描述及协作者等。
        在此基础上，创建任务时可以设置截止时间和重复规则，将任务设置为定期执行的重复任务。通过添加协作者，则可以让其他用户协同完成该任务。
        此外，接口也提供了一些支持自定义内容的字段，调用方可以实现定制化效果，如完成任务后跳转到指定结束界面。
        """
        ...

    def patch_task(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task/patch

        该接口用于修改任务的标题、描述、时间、来源等相关信息
        """
        ...

    def complete_task(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task/complete

        该接口用于将任务状态修改为“已完成”。
        完成任务是指整个任务全部完成，而不支持执行者分别完成任务，执行成功后，任务对所有关联用户都变为完成状态。
        """
        ...

    def uncomplete_task(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task/uncomplete

        该接口用于取消任务的已完成状态
        """
        ...

    def delete_task(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task/delete

        该接口用于删除任务
        """
        ...

    def list_task(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task/list

        以分页的方式获取任务列表。当使用user_access_token时，获取与该用户身份相关的所有任务。当使用tenant_access_token时，获取以该应用身份通过“创建任务“接口创建的所有任务（并非获取该应用所在租户下所有用户创建的任务）。
        本接口支持通过任务创建时间以及任务的完成状态对任务进行过滤。
        """
        ...

    def get_task(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task/get

        该接口用于获取任务详情，包括任务标题、描述、时间、来源等信息
        """
        ...

    def create_task_reminder(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task-reminder/create

        该接口用于创建任务的提醒时间。提醒时间在截止时间基础上做偏移，但是偏移后的结果不能早于当前时间。
        """
        ...

    def delete_task_reminder(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task-reminder/delete

        删除提醒时间，返回结果状态
        """
        ...

    def list_task_reminder(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task-reminder/list

        返回提醒时间列表，支持分页，最大值为50
        """
        ...

    def create_task_follower(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task-follower/create

        该接口用于创建任务关注人。可以一次性添加多位关注人。关注人ID要使用表示用户的ID。
        """
        ...

    def delete_task_follower(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task-follower/delete

        该接口用于删除任务关注人
        """
        ...

    def batch_delete_follower_task(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task/batch_delete_follower

        该接口用于批量删除关注人
        """
        ...

    def list_task_follower(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task-follower/list

        该接口用于查询任务关注人列表，支持分页，最大值为50
        """
        ...

    def create_task_collaborator(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task-collaborator/create

        该接口用于新增任务执行者，一次性可以添加多个执行者。
        只有任务的创建者和执行者才能添加执行者，关注人无权限添加。
        """
        ...

    def delete_task_collaborator(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task-collaborator/delete

        该接口用于删除任务执行者
        """
        ...

    def batch_delete_collaborator_task(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task/batch_delete_collaborator

        该接口用于批量删除执行者
        """
        ...

    def list_task_collaborator(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task-collaborator/list

        该接口用于查询任务执行者列表，支持分页，最大值为50
        """
        ...

    def create_task_comment(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task-comment/create

        该接口用于创建和回复任务的评论。当parent_id字段为0时，为创建评论；当parent_id不为0时，为回复某条评论
        """
        ...

    def delete_task_comment(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task-comment/delete

        该接口用于通过评论ID删除评论
        """
        ...

    def update_task_comment(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task-comment/update

        该接口用于更新评论内容
        """
        ...

    def get_task_comment(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task-comment/get

        该接口用于通过评论ID获取评论详情
        """
        ...

    def list_task_comment(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/task-v1/task-comment/list

        该接口用于查询任务评论列表，支持分页，最大值为100
        """
        ...
