"""DO NOT EDIT THIS FILE!

This file is auto generated by feishu rest api description.
"""


from typing import TYPE_CHECKING, overload

from pydantic import BaseModel, parse_obj_as

if TYPE_CHECKING:
    from feishukit.response import Response


class VcClient:
    def __init__(self, feishu):
        self._feishu = feishu

    def apply_reserve(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/reserve/apply

        创建一个会议预约。
        """
        ...

    def update_reserve(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/reserve/update

        更新一个预约
        """
        ...

    def delete_reserve(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/reserve/delete

        删除一个预约
        """
        ...

    def get_reserve(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/reserve/get

        获取一个预约的详情
        """
        ...

    def get_active_meeting_reserve(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/reserve/get_active_meeting

        获取一个预约的当前活跃会议
        """
        ...

    def get_meeting(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/meeting/get

        获取一个会议的详细数据
        """
        ...

    def list_by_no_meeting(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/meeting/list_by_no

        获取指定时间范围（90天内)会议号关联的会议简要信息列表
        """
        ...

    def invite_meeting(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/meeting/invite

        邀请参会人进入会议
        """
        ...

    def kickout_meeting(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/meeting/kickout

        将参会人从会议中移除
        """
        ...

    def set_host_meeting(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/meeting/set_host

        设置会议的主持人
        """
        ...

    def end_meeting(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/meeting/end

        结束一个进行中的会议
        """
        ...

    def start_meeting_recording(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/meeting-recording/start

        在会议中开始录制。
        """
        ...

    def stop_meeting_recording(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/meeting-recording/stop

        在会议中停止录制。
        """
        ...

    def get_meeting_recording(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/meeting-recording/get

        获取一个会议的录制文件。
        """
        ...

    def set_permission_meeting_recording(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/meeting-recording/set_permission

        将一个会议的录制文件授权给组织、用户或公开到公网
        """
        ...

    def get_daily_report(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/report/get_daily

        获取一段时间内组织的每日会议使用报告。
        """
        ...

    def get_top_user_report(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/report/get_top_user

        获取一段时间内组织内会议使用的top用户列表。
        """
        ...

    def list_room(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room/list

        该接口可以用来查询某个会议室层级下会议室列表
        """
        ...

    def get_room(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room/get

        该接口可以使用会议室ID查询会议室详情
        """
        ...

    def mget_room(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room/mget

        该接口可以使用会议室ID批量查询会议室详情
        """
        ...

    def create_room(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room/create

        该接口用于创建会议室
        """
        ...

    def patch_room(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room/patch

        该接口可以用来更新某个会议室的信息
        """
        ...

    def delete_room(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room/delete

        该接口可以用来删除某个会议室
        """
        ...

    def search_room(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room/search

        该接口可以用来搜索会议室，支持使用关键词进行搜索，也支持使用自定义会议室ID进行查询
        """
        ...

    def list_room_level(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room_level/list

        该接口用来查询某个会议室层级下的子层级列表
        """
        ...

    def get_room_level(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room_level/get

        该接口可以使用会议室层级ID查询会议室层级详情
        """
        ...

    def mget_room_level(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room_level/mget

        该接口可以使用会议室层级ID批量查询会议室层级详情
        """
        ...

    def create_room_level(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room_level/create

        该接口用于创建会议室层级
        """
        ...

    def patch_room_level(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room_level/patch

        该接口可以用来更新某个会议室层级的信息
        """
        ...

    def del_room_level(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room_level/del

        该接口可以用来删除某个会议室层级
        """
        ...

    def search_room_level(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room_level/search

        该接口可以用来搜索会议室层级，支持使用自定义会议室层级ID进行查询
        """
        ...

    def create_scope_config(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/scope_config/create

        该接口可以用来设置某个会议层级范围下或者某个会议室的配置
        """
        ...

    def get_scope_config(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/scope_config/get

        该接口可以用来查询某个会议层级范围下或者某个会议室的配置
        """
        ...

    def reserve_scope_reserve_config(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/reserve_config/reserve_scope

        获取会议室预定范围
        """
        ...

    def patch_reserve_config(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/reserve_config/patch

        更新会议室预定范围
        """
        ...

    def meeting_list_export(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/export/meeting_list

        导出会议明细，具体权限要求请参考「导出概述」
        """
        ...

    def participant_list_export(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/export/participant_list

        导出某个会议的参会人详情列表，具体权限要求请参考「导出概述」
        """
        ...

    def participant_quality_list_export(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/export/participant_quality_list

        导出某场会议某个参会人的音视频&共享质量数据
        ，具体权限要求请参考「导出概述」
        """
        ...

    def resource_reservation_list_export(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/export/resource_reservation_list

        导出会议室预定数据，具体权限要求请参考「导出概述」
        """
        ...

    def get_export(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/export/get

        查看异步导出的进度
        """
        ...

    def download_export(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/export/download

        下载导出文件
        """
        ...

    def list_alert(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/alert/list

        获取特定条件下租户的设备告警记录
        """
        ...

    def query_room_config(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room_config/query

        查询一个范围内的会议室配置。
        """
        ...

    def set_room_config(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/vc-v1/room_config/set

        设置一个范围内的会议室配置。
        """
        ...
