"""DO NOT EDIT THIS FILE!

This file is auto generated by feishu rest api description.
"""


from typing import TYPE_CHECKING, overload

from pydantic import BaseModel, parse_obj_as

if TYPE_CHECKING:
    from feishukit.response import Response


class VerificationInformationClient:
    def __init__(self, feishu):
        self._feishu = feishu

    def get_verification(
        self,
    ):
        """
        https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/verification-v1/verification/get

        获取企业主体名称、是否认证等信息。
        """
        ...
